name: Deploy

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed
    branches:
      - master

jobs:
  deploy-metadata:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Add SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_META_KEY }}

      - name: Deploy metadata
        run: ./etc/deploy.sh

  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Add SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_DOCS_KEY }}

      - name: Deploy docs
        run: ./etc/deploy-docs.sh

  deploy-s3:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy resources
        run: |
          aws s3 sync --quiet resources s3://${{ secrets.AWS_BUCKET_NAME }}
          aws s3 sync --quiet resources/payment_methods s3://${{ secrets.AWS_BUCKET_NAME }}/payment-methods
          aws s3 sync --quiet resources/payout_methods s3://${{ secrets.AWS_BUCKET_NAME }}/payout-methods
          aws s3 sync --quiet resources/payment_providers s3://${{ secrets.AWS_BUCKET_NAME }}/payment-providers

