name: Validate

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
            bin
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          export PATH="$HOME/.composer/vendor/bin:$PATH"
          composer self-update
          composer install -o --ignore-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        
      - name: Upload bin folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bin-folder
          path: bin

  validate-json:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            vendor
            bin
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Download bin folder
        uses: actions/download-artifact@v4
        with:
          name: bin-folder
          path: bin
      - name: Make validate-json executable
        run: chmod +x ./bin/validate-json
      - name: Run validate
        run: ./etc/validate.sh

  phpunit:
    needs: validate-json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            vendor
            bin
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6.8
          memory_limit: 1G
          configuration: phpunit.xml
